### ISSUE TITLE
Waiting for device - stuck on droidboot

### ISSUE THREAD

**Issue by reyhansofian** [sigo/asus-zenfone-5-root#1]
Hi, I've tried to run `./root.sh`
but, it stuck on droidboot. On terminal show `< waiting for device >`  and do nothing. 
Is there a way to solve it?

**Comment by reyhansofian** [comment]
and now it's stuck on fastboot

```
$home:~/asus-zenfone-5-root-master$ ./root.sh 
Connect your phone with computer and prepare to root
USB debugging mode must be enabled
Do not disconnect USB cable while rooting
Whole process can take up to 10 minutes, please be patient

Unlocking fastboot
--- log ---
< waiting for device >
```

**Comment by sigo** [comment]
Hi @reyhansofian, I've not been available for a while. Do you still need help?

It looks that you have one of these problem:
- udev rules or permissions at the linux machine,
- phone doesn't have enabled USB debugging mode (read more at the manual).

This isn't problem with the script itself.

You can find solution for your distro with google-phrase:

```
<distro-name> waiting for device android
```

For eg:

```
ubuntu waiting for device android
```

or

```
ubuntu android udev rules
```

The other solution **(not recommended)** is running script as root. Before running it as root, make sure the **adb daemon** isn't running.
